{% set name = "python-forge" %}
{% set version = "18.6.0" %}
{% set hash_val = "d4fda61e8f97a4a3505c576f0c40a12b70dab424ea4483333aaebe8a7f165fb9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Note: currently published on PyPI as a wheel with no sdist, so using source archive instead
  url: https://github.com/dfee/forge/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - forge
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/dfee/forge
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Forge (python signatures) for fun and profit'
  description: |
    Forge is an elegant python package for revising function signatures at runtime.
    This library aims is to help you write better, more literate code with less boilerplate.
  doc_url: https://python-forge.readthedocs.io/en/latest/
  dev_url: https://github.com/dfee/forge

extra:
  recipe-maintainers:
    - jwcook
